import type { SymbolDef } from '../types.ts';
import { circle, hline, poly, rect, vline, line, contact } from '../shape.ts';

/** 引込元・引込点・責任分界点まわり（ナレッジベース 系統構成 1〜4 に対応） */
export const incomingSymbols: SymbolDef[] = [
  {
    id: 'pole-utility',
    status: 'awaiting-sample',
    statusNote: '代表図面の到着後に描き直します。',
    abbr: '電柱',
    nameJa: '電柱（電力会社所有）',
    category: 'incoming',
    tags: ['引込元', '電力会社', 'パターンA'],
    box: { w: 44, h: 44 },
    shapes: [
      vline(12, 4, 44, { sw: 1.6 }),
      hline(10, 3, 21),
      hline(16, 5, 19),
      hline(30, 12, 44),
    ],
    ports: [{ id: 'out', x: 44, y: 30, dir: 'right', role: 'line' }],
    fields: [{ key: 'poleNo', label: '電柱番号', type: 'text' }],
    note: '引込元パターンA。電力会社所有の電柱。',
    review: '電柱の描き方（腕金付きの柱／円のみ／点線枠＋文字）は現場の図面に合わせて要調整。',
  },
  {
    id: 'pole-customer',
    status: 'awaiting-sample',
    statusNote: '代表図面の到着後に描き直します。',
    abbr: '客柱',
    nameJa: 'お客様電柱',
    category: 'incoming',
    tags: ['需要家', 'PAS', '電柱上'],
    box: { w: 44, h: 44 },
    shapes: [
      vline(12, 4, 44, { sw: 1.6 }),
      hline(10, 3, 21),
      hline(16, 5, 19),
      hline(30, 12, 44),
    ],
    ports: [{ id: 'out', x: 44, y: 30, dir: 'right', role: 'line' }],
    fields: [{ key: 'poleNo', label: '電柱番号', type: 'text' }],
    note: 'PASは電柱上に設置するため、図面上「お客様電柱」として描かれる場合がある。',
  },
  {
    id: 'cabinet',
    status: 'awaiting-sample',
    statusNote: '代表図面の到着後に描き直します。',
    abbr: 'CAB',
    nameJa: 'キャビネット',
    nameFormal: '地上設置金属製ボックス',
    category: 'incoming',
    tags: ['引込元', 'パターンB', '地上'],
    box: { w: 44, h: 44 },
    shapes: [
      rect(6, 8, 30, 28),
      hline(38, 10, 32),
      hline(22, 36, 44),
    ],
    ports: [{ id: 'out', x: 44, y: 22, dir: 'right', role: 'line' }],
    note: '引込元パターンB。電力会社との連携点になる場合あり。中身はモールドディスコン／三極連動ティー型シェルター。',
  },
  {
    id: 'incoming-point',
    status: 'awaiting-sample',
    statusNote: '代表図面の到着後に描き直します。',
    abbr: '引込点',
    nameJa: '引込点',
    category: 'incoming',
    tags: ['引込', '受電点'],
    box: { w: 40, h: 40 },
    shapes: [vline(20, 0, 16), circle(20, 20, 4), vline(20, 24, 40)],
    ports: [
      { id: 'in', x: 20, y: 0, dir: 'up', role: 'line' },
      { id: 'out', x: 20, y: 40, dir: 'down', role: 'line' },
    ],
    note: '3点一致（約99%）の場合、この直下とPASの間に分界点の横線を引く。',
  },
  {
    id: 'mold-discon',
    status: 'awaiting-sample',
    statusNote: '代表図面の到着後に描き直します。',
    abbr: 'MDS',
    nameJa: 'モールドディスコン',
    category: 'incoming',
    tags: ['キャビネット', 'パターンA'],
    box: { w: 44, h: 48 },
    shapes: [
      vline(22, 0, 10),
      rect(8, 10, 28, 28),
      hline(14.5, 17, 27),
      contact(22, 16),
      contact(22, 32),
      line(22, 30.2, 31, 18),
      vline(22, 38, 48),
    ],
    ports: [
      { id: 'in', x: 22, y: 0, dir: 'up', role: 'line' },
      { id: 'out', x: 22, y: 48, dir: 'down', role: 'line' },
    ],
    note: 'キャビネット内パターンA。',
    review: '断路器記号を箱に入れた表現にしている。実際の図面での描き方を確認したい。',
  },
  {
    id: 'tee-shelter',
    status: 'awaiting-sample',
    statusNote: '代表図面の到着後に描き直します。',
    abbr: 'TS',
    nameJa: '三極連動ティー型シェルター',
    category: 'incoming',
    tags: ['キャビネット', 'パターンB'],
    box: { w: 44, h: 48 },
    shapes: [
      vline(22, 0, 10),
      rect(8, 10, 28, 28),
      hline(17, 14, 30),
      vline(22, 17, 33),
      vline(22, 38, 48),
    ],
    ports: [
      { id: 'in', x: 22, y: 0, dir: 'up', role: 'line' },
      { id: 'out', x: 22, y: 48, dir: 'down', role: 'line' },
    ],
    note: 'キャビネット内パターンB。',
    review: '「ティー型」をT字で表現している。実際の図記号を確認したい。',
  },
  {
    id: 'cable-head',
    status: 'awaiting-sample',
    statusNote: '代表図面の到着後に描き直します。',
    abbr: 'CH',
    nameJa: '高圧ケーブル端末',
    nameFormal: 'ケーブル終端接続部',
    category: 'incoming',
    tags: ['受電点', 'ケーブルヘッド', '端末処理'],
    box: { w: 40, h: 40 },
    shapes: [
      vline(20, 0, 12),
      poly([12, 12, 28, 12, 23, 28, 17, 28], { close: true, fill: 'none' }),
      vline(20, 28, 40),
    ],
    ports: [
      { id: 'in', x: 20, y: 0, dir: 'up', role: 'line' },
      { id: 'out', x: 20, y: 40, dir: 'down', role: 'line' },
    ],
    note: '電気設備側の引込点は、図面上まずこの高圧ケーブル端末が該当する。',
  },
  {
    id: 'boundary-both',
    status: 'awaiting-sample',
    statusNote: '記載文言は確定済み。横線の引き方は代表図面の到着後に確認します。',
    abbr: '分界点',
    nameJa: '財産・責任分界点（3点一致）',
    category: 'boundary',
    tags: ['3点一致', '分界点'],
    box: { w: 64, h: 24 },
    shapes: [vline(32, 0, 24), hline(12, 0, 64)],
    ports: [
      { id: 'in', x: 32, y: 0, dir: 'up', role: 'line' },
      { id: 'out', x: 32, y: 24, dir: 'down', role: 'line' },
    ],
    defaultLabel: '財産・責任分界点',
    note: '3点一致（全体の約99%）。引込点の図記号とPASの間に横線を引き、この文言を記載する。',
  },
  {
    id: 'boundary-property',
    status: 'awaiting-sample',
    statusNote: '記載文言は確定済み。横線の引き方は代表図面の到着後に確認します。',
    abbr: '財産',
    nameJa: '財産分界点（3点不一致のとき）',
    category: 'boundary',
    tags: ['3点不一致', '分界点'],
    box: { w: 64, h: 24 },
    shapes: [vline(32, 0, 24), hline(12, 0, 64)],
    ports: [
      { id: 'in', x: 32, y: 0, dir: 'up', role: 'line' },
      { id: 'out', x: 32, y: 24, dir: 'down', role: 'line' },
    ],
    defaultLabel: '財産分界点',
    note: '3点不一致（全体の約1%）。引込点と同一地点に財産分界点を記載する。',
  },
  {
    id: 'boundary-safety',
    status: 'awaiting-sample',
    statusNote: '記載文言は確定済み。横線の引き方は代表図面の到着後に確認します。',
    abbr: '責任',
    nameJa: '責任分界点（3点不一致のとき）',
    category: 'boundary',
    tags: ['3点不一致', '分界点', 'LBS', 'VCB'],
    box: { w: 64, h: 24 },
    shapes: [vline(32, 0, 24), hline(12, 0, 64, { sw: 1 })],
    ports: [
      { id: 'in', x: 32, y: 0, dir: 'up', role: 'line' },
      { id: 'out', x: 32, y: 24, dir: 'down', role: 'line' },
    ],
    defaultLabel: '責任分界点',
    note: '3点不一致のとき、該当するLBSまたはVCBの図記号の中央に横線を引いて記載する（このパターンの約99%はLBSかVCB）。',
  },
];
