import type { SymbolDef } from '../types.ts';
import { circle, hline, line, rect, text, vline } from '../shape.ts';

/** 計器（低圧側。図面に記載することはほぼないが、データとしては保持する） */
const meter = (id: string, label: string, nameJa: string, size = 11): SymbolDef => ({
  id,
  abbr: label,
  nameJa,
  category: 'instrument',
  tags: ['計器', '低圧'],
  box: { w: 36, h: 32 },
  shapes: [hline(16, 0, 6), circle(19, 16, 13), text(19, 16, label, { size })],
  ports: [{ id: 'in', x: 0, y: 16, dir: 'left', role: 'secondary' }],
  status: 'confirmed',
  statusNote: 'この形でOK。低圧設備のため図面に記載することはほぼないが、データとしては保持する。',
});

/** 計器用変成器・計器 */
export const instrumentSymbols: SymbolDef[] = [
  {
    id: 'vct',
    abbr: 'VCT',
    nameJa: '計器用変圧変流器（電力会社の計器用変成器）',
    category: 'instrument',
    tags: ['電力会社', '課金用', '電柱上', 'キュービクル内'],
    box: { w: 72, h: 64 },
    shapes: [
      vline(22, 0, 64),
      rect(6, 8, 56, 48),
      hline(24, 22, 32),
      circle(40, 24, 8),
      circle(50, 24, 8),
      hline(24, 58, 72),
      circle(22, 42, 9),
      hline(42, 31, 72),
    ],
    ports: [
      { id: 'in', x: 22, y: 0, dir: 'up', role: 'line' },
      { id: 'out', x: 22, y: 64, dir: 'down', role: 'line' },
      { id: 'sec-vt', x: 72, y: 24, dir: 'right', role: 'secondary', label: 'VT二次' },
      { id: 'sec-ct', x: 72, y: 42, dir: 'right', role: 'secondary', label: 'CT二次' },
    ],
    fields: [
      {
        key: 'location',
        label: 'VCTの位置',
        type: 'select',
        options: [
          { value: 'pole', label: '電柱上（約70%）' },
          { value: 'indoor', label: '電気設備内（キュービクル／電気室・約30%）' },
        ],
        defaultValue: 'pole',
      },
    ],
    status: 'confirmed',
    statusNote: '見本図面のとおり、実線の箱の中に上段：VT（二重丸）、下段：CT（単円）を配置しました。',
    note: '電気設備内に入る場合の挿入位置は、PFS形ならケーブルとLBSの間、CB形ならケーブルとDSの間。',
  },
  {
    id: 'ct',
    abbr: 'CT',
    nameJa: '計器用変流器',
    category: 'instrument',
    tags: ['CB形', 'OCR'],
    box: { w: 52, h: 44 },
    shapes: [
      vline(20, 0, 44),
      circle(20, 22, 11),
      line(9, 33, 31, 11),
      text(26, 29, '3', { size: 9 }),
      hline(22, 31, 52),
    ],
    ports: [
      { id: 'in', x: 20, y: 0, dir: 'up', role: 'line' },
      { id: 'out', x: 20, y: 44, dir: 'down', role: 'line' },
      { id: 'sec', x: 52, y: 22, dir: 'right', role: 'secondary', label: 'OCRへ' },
    ],
    fields: [
      { key: 'count', label: '個数', type: 'number', unit: '個', defaultValue: 3, help: '斜線の横に記載する数' },
      { key: 'ratio', label: '変流比', type: 'text', help: '例: 100/5A' },
    ],
    status: 'open-question',
    statusNote: '見本図面（円＋斜線＋3）をCTとして写しました。',
    review: 'この記号はCTでしょうか、それともZCTでしょうか。斜線の横の「3」は個数（3相分）という理解で合っていますか。',
    note: 'CB形では、VCBのすぐ下にCT、その次にOCRが入る。',
  },
  {
    id: 'zct',
    abbr: 'ZCT',
    nameJa: '零相変流器',
    nameFormal: 'ゼロカーレントトランスフォーマー',
    category: 'instrument',
    tags: ['PAS', 'GR', 'DGR', '地絡'],
    box: { w: 44, h: 40 },
    shapes: [
      vline(22, 0, 40),
      circle(22, 20, 9),
      line(15.5, 26.5, 28.5, 13.5),
      hline(20, 31, 44),
    ],
    ports: [
      { id: 'in', x: 22, y: 0, dir: 'up', role: 'line' },
      { id: 'out', x: 22, y: 40, dir: 'down', role: 'line' },
      { id: 'sec', x: 44, y: 20, dir: 'right', role: 'control', label: 'GR/DGRへ' },
    ],
    status: 'confirmed',
    statusNote: '見本図面のとおり、円の中に斜線を入れる形にしました。',
    note: 'GR方式・DGR方式のPASに入る。',
    review: '見本図面ではZCTの下に接地記号が付いていました。これはZCT記号の一部（常に描く）でしょうか。',
  },
  {
    id: 'vt',
    abbr: 'VT',
    nameJa: '計器用変圧器',
    nameFormal: 'ボルテージトランスフォーマー',
    category: 'instrument',
    tags: ['CB形', 'DS', 'PAS内蔵'],
    box: { w: 60, h: 30 },
    shapes: [hline(15, 0, 8), circle(19, 15, 11), circle(35, 15, 11), hline(15, 46, 60)],
    ports: [
      { id: 'in', x: 0, y: 15, dir: 'left', role: 'line' },
      { id: 'sec', x: 60, y: 15, dir: 'right', role: 'secondary', label: '計器・継電器へ' },
    ],
    fields: [{ key: 'ratio', label: '変圧比', type: 'text', help: '図面の記載例: 6600/110V' }],
    status: 'confirmed',
    statusNote: '見本図面のとおり、横向きに並べた二重丸（接地なし）にしました。',
    note: '母線から横に分岐し、手前にPFが入る。図面の記載例「VT＋PF 6600/110V」。CB形ではDSの次に並列接続（直列ではない）。',
  },
  meter('meter-wh', 'Wh', '電力量計', 10),
  meter('meter-a', 'A', '電流計'),
  meter('meter-v', 'V', '電圧計'),
  {
    ...meter('meter-pf', 'cosθ', '位相計（力率計）', 8),
    tags: ['計器', '低圧', '力率', '位相'],
    status: 'open-question',
    statusNote: '新規追加。丸の中に cosθ と表記しています。この表記でよいかご確認ください。',
    review: '丸の中の表記を「cosθ」としています。図面での実際の表記（COSθ / cosφ 等）をご確認ください。',
  },
];
