import type { SymbolDef } from '../types.ts';
import { circle, hline, rect, text, vline } from '../shape.ts';

/** 計器用変成器・計器 */
export const instrumentSymbols: SymbolDef[] = [
  {
    id: 'vct',
    abbr: 'VCT',
    nameJa: '計器用変圧変流器（電力会社の計器用変成器）',
    category: 'instrument',
    tags: ['電力会社', '課金用', '電柱上', 'キュービクル内'],
    box: { w: 48, h: 56 },
    shapes: [
      vline(24, 0, 56),
      rect(4, 6, 40, 40, { dash: '4 3' }),
      circle(24, 18, 7),
      hline(18, 31, 48),
      hline(33, 19, 24),
      circle(14, 33, 5),
      circle(14, 41, 5),
    ],
    ports: [
      { id: 'in', x: 24, y: 0, dir: 'up', role: 'line' },
      { id: 'out', x: 24, y: 56, dir: 'down', role: 'line' },
      { id: 'sec', x: 48, y: 18, dir: 'right', role: 'secondary', label: '電力量計へ' },
    ],
    fields: [
      {
        key: 'location',
        label: 'VCTの位置',
        type: 'select',
        options: [
          { value: 'pole', label: '電柱上（約70%）' },
          { value: 'indoor', label: '電気設備内（キュービクル／電気室・約30%）' },
        ],
        defaultValue: 'pole',
      },
    ],
    note: '電気設備内に入る場合の挿入位置は、PFS形ならケーブルとLBSの間、CB形ならケーブルとDSの間。',
  },
  {
    id: 'ct',
    abbr: 'CT',
    nameJa: '計器用変流器',
    category: 'instrument',
    tags: ['CB形', 'OCR'],
    box: { w: 44, h: 40 },
    shapes: [vline(22, 0, 40), circle(22, 20, 8), hline(20, 30, 44)],
    ports: [
      { id: 'in', x: 22, y: 0, dir: 'up', role: 'line' },
      { id: 'out', x: 22, y: 40, dir: 'down', role: 'line' },
      { id: 'sec', x: 44, y: 20, dir: 'right', role: 'secondary', label: 'OCRへ' },
    ],
    fields: [{ key: 'ratio', label: '変流比', type: 'text', help: '例: 100/5A' }],
    note: 'CB形では、VCBのすぐ下にCT、その次にOCRが入る。',
  },
  {
    id: 'zct',
    abbr: 'ZCT',
    nameJa: '零相変流器',
    nameFormal: 'ゼロカーレントトランスフォーマー',
    category: 'instrument',
    tags: ['PAS', 'GR', 'DGR', '地絡'],
    box: { w: 44, h: 40 },
    shapes: [vline(22, 0, 40), circle(22, 20, 8), hline(20, 30, 44)],
    ports: [
      { id: 'in', x: 22, y: 0, dir: 'up', role: 'line' },
      { id: 'out', x: 22, y: 40, dir: 'down', role: 'line' },
      { id: 'sec', x: 44, y: 20, dir: 'right', role: 'control', label: 'GR/DGRへ' },
    ],
    note: 'GR方式・DGR方式のPASに入る。',
    review: 'CTと同一形状（円）で、区別は文字（ZCT）のみとしている。図面上もこの扱いで問題ないか確認したい。',
  },
  {
    id: 'vt',
    abbr: 'VT',
    nameJa: '計器用変圧器',
    nameFormal: 'ボルテージトランスフォーマー',
    category: 'instrument',
    tags: ['CB形', 'DS', 'PAS内蔵'],
    box: { w: 44, h: 56 },
    shapes: [
      vline(22, 0, 10),
      circle(22, 17, 7),
      circle(22, 26, 7),
      vline(22, 33, 44),
      hline(44, 13, 31),
      hline(48, 16.5, 27.5),
      hline(52, 19.5, 24.5),
    ],
    ports: [
      { id: 'in', x: 22, y: 0, dir: 'up', role: 'line' },
      { id: 'sec', x: 44, y: 22, dir: 'right', role: 'secondary', label: '計器へ' },
    ],
    fields: [{ key: 'ratio', label: '変圧比', type: 'text', help: '例: 6600/110V' }],
    note: 'CB形ではDSの次に並列接続（直列ではない）。PAS内蔵のパターンもある。',
  },
  {
    id: 'meter-wh',
    abbr: 'Wh',
    nameJa: '電力量計',
    category: 'instrument',
    tags: ['計器', '課金'],
    box: { w: 36, h: 32 },
    shapes: [hline(16, 0, 6), circle(19, 16, 13), text(19, 16, 'Wh', { size: 10 })],
    ports: [{ id: 'in', x: 0, y: 16, dir: 'left', role: 'secondary' }],
  },
  {
    id: 'meter-a',
    abbr: 'A',
    nameJa: '電流計',
    category: 'instrument',
    tags: ['計器'],
    box: { w: 36, h: 32 },
    shapes: [hline(16, 0, 6), circle(19, 16, 13), text(19, 16, 'A', { size: 11 })],
    ports: [{ id: 'in', x: 0, y: 16, dir: 'left', role: 'secondary' }],
  },
  {
    id: 'meter-v',
    abbr: 'V',
    nameJa: '電圧計',
    category: 'instrument',
    tags: ['計器'],
    box: { w: 36, h: 32 },
    shapes: [hline(16, 0, 6), circle(19, 16, 13), text(19, 16, 'V', { size: 11 })],
    ports: [{ id: 'in', x: 0, y: 16, dir: 'left', role: 'secondary' }],
  },
];
