import type { SymbolDef } from '../types.ts';
import { circle, hline, line, path, poly, rect, text, vline } from '../shape.ts';

/** 一点鎖線（受電設備エリアの外枠に使う） */
export const DASH_DOT = '9 3 2 3';

/** 進相設備・電源設備・外枠・結線要素 */
export const miscSymbols: SymbolDef[] = [
  {
    id: 'sc',
    abbr: 'SC',
    nameJa: '進相コンデンサ',
    category: 'compensation',
    tags: ['コンデンサ', '進相設備', '力率改善'],
    box: { w: 44, h: 48 },
    shapes: [vline(22, 0, 10), rect(7, 10, 30, 30), vline(22, 10, 21), hline(21, 11, 33), hline(26, 11, 33)],
    ports: [{ id: 'in', x: 22, y: 0, dir: 'up', role: 'line' }],
    fields: [
      { key: 'phase', label: '相', type: 'text', defaultValue: '3φ' },
      { key: 'capacity', label: '容量', type: 'number', unit: 'kvar' },
      { key: 'ratedVoltage', label: '定格電圧', type: 'text', unit: 'V' },
    ],
    status: 'confirmed',
    statusNote: '見本図面のとおり、四角の中にコンデンサ（2枚の板）を描く形にしました。',
    note: '変圧器と並列に入るパターンがある。台数は1台〜複数台。記載例「SC 3φ106kvar 7020V」。',
  },
  {
    id: 'generator',
    abbr: 'G',
    nameJa: '発電機',
    category: 'source',
    tags: ['発電機', '非常用', '常用'],
    box: { w: 40, h: 44 },
    shapes: [vline(20, 0, 10), circle(20, 24, 14), text(20, 24, 'G', { size: 13 })],
    ports: [{ id: 'out', x: 20, y: 0, dir: 'up', role: 'line' }],
    fields: [
      {
        key: 'voltageClass',
        label: '電圧区分',
        type: 'select',
        options: [
          { value: 'high', label: '高圧発電機' },
          { value: 'low', label: '低圧発電機' },
        ],
      },
      {
        key: 'usage',
        label: '用途区分',
        type: 'select',
        options: [
          { value: 'normal', label: '常用型（常に稼働）' },
          { value: 'emergency', label: '非常用型（非常時のみ稼働）' },
        ],
      },
      { key: 'capacity', label: '容量', type: 'number', unit: 'kVA' },
      { key: 'place', label: '設置場所', type: 'text', help: '非常用発電機の場合は図面に明記する' },
    ],
    status: 'confirmed',
    statusNote: 'このマークでOK。',
  },
  {
    id: 'pv',
    abbr: 'PV',
    nameJa: '太陽光発電設備',
    category: 'source',
    tags: ['太陽光', '発電所', '再エネ'],
    box: { w: 44, h: 44 },
    shapes: [
      rect(10, 14, 26, 18),
      line(10, 32, 36, 14),
      line(1, 3, 9, 10),
      poly([6, 10, 10, 11.5, 8.5, 7.5], { close: true, fill: 'solid' }),
      line(9, 0, 17, 7),
      poly([14, 7, 18, 8.5, 16.5, 4.5], { close: true, fill: 'solid' }),
      vline(23, 32, 44),
    ],
    ports: [{ id: 'out', x: 23, y: 44, dir: 'down', role: 'line' }],
    fields: [
      { key: 'capacity', label: '設備規模', type: 'number', unit: 'kW' },
      { key: 'pcsCount', label: 'PCS台数', type: 'number', unit: '台' },
    ],
    status: 'awaiting-sample',
    statusNote: '代表図面の到着後に確認・修正します。',
    note: '太陽光発電設備の規模（大きさ）を単線結線図に情報として載せる。',
  },
  {
    id: 'battery',
    abbr: 'BATT',
    nameJa: '蓄電池（系統用蓄電所）',
    category: 'source',
    tags: ['蓄電', '系統用蓄電所'],
    box: { w: 40, h: 44 },
    shapes: [
      vline(20, 0, 12),
      hline(12, 8, 32),
      hline(16, 14, 26),
      hline(22, 8, 32),
      hline(26, 14, 26),
      vline(20, 26, 44),
    ],
    ports: [{ id: 'out', x: 20, y: 0, dir: 'up', role: 'line' }],
    fields: [
      { key: 'capacity', label: '蓄電ユニット規模', type: 'number', unit: 'kWh' },
      { key: 'gridPoleNo', label: '連携する電柱番号', type: 'text' },
      { key: 'demandSite', label: '需要場所名', type: 'text' },
    ],
    status: 'awaiting-sample',
    statusNote: '系統用蓄電所の図面をいただいてから、それを参考に作成します。',
    note: '構成はほぼ固定で、変更点は連携する電柱番号や需要場所名程度。',
  },
  {
    id: 'bus',
    abbr: '母線',
    nameJa: '母線',
    category: 'wiring',
    tags: ['母線', '分岐'],
    box: { w: 80, h: 12 },
    shapes: [hline(6, 0, 80, { sw: 3 })],
    ports: [
      { id: 'l', x: 0, y: 6, dir: 'left', role: 'line' },
      { id: 'r', x: 80, y: 6, dir: 'right', role: 'line' },
      { id: 'in', x: 40, y: 0, dir: 'up', role: 'line' },
    ],
    status: 'confirmed',
    statusNote: 'このままでOK。',
    note: '線と線の交点に点（接続点マーク）は置かない。',
  },
  {
    id: 'ground-line',
    abbr: '地表面',
    nameJa: '地表面・建物境界の線',
    category: 'wiring',
    tags: ['埋設', '地表面', 'ケーブル'],
    box: { w: 120, h: 10 },
    shapes: [hline(5, 0, 120, { sw: 2.2 })],
    ports: [
      { id: 'l', x: 0, y: 5, dir: 'left' },
      { id: 'r', x: 120, y: 5, dir: 'right' },
    ],
    status: 'confirmed',
    statusNote: '見本図面（埋ケのケーブル）にあった太い横線を記号にしました。',
    note: '埋設ケーブルが地表面を横切る箇所に引く。',
  },
  {
    id: 'enclosure-cubicle',
    abbr: '外箱',
    nameJa: 'キュービクル・電気室の外箱',
    category: 'enclosure',
    tags: ['キュービクル', '電気室', 'オープンフレーム式'],
    box: { w: 130, h: 80 },
    shapes: [rect(0, 0, 130, 80)],
    ports: [],
    fields: [
      {
        key: 'form',
        label: '形態',
        type: 'select',
        options: [
          { value: 'cubicle', label: 'キュービクル式' },
          { value: 'room-cubicle', label: '電気室（内にキュービクル）' },
          { value: 'room-open', label: 'オープンフレーム式' },
        ],
        help: '「開放型」等の表記は使わず「オープンフレーム式」に統一する。',
      },
      {
        key: 'placement',
        label: '設置場所',
        type: 'select',
        options: [
          { value: 'indoor', label: '屋内' },
          { value: 'rooftop', label: '屋上' },
          { value: 'outdoor', label: '屋外（地上）' },
          { value: 'semi-outdoor', label: '半屋外' },
        ],
        allowFreeInput: true,
      },
      { key: 'floor', label: '階層', type: 'text', help: '例: 2階 / 中2階' },
      { key: 'detail', label: '場所の補足', type: 'text', help: '例: 駐車場横' },
    ],
    defaultLabel: 'キュービクル式（2階屋外）',
    status: 'confirmed',
    statusNote: '見本図面のとおり実線の四角にし、ラベルは枠の左上（外側）に置きます。',
    note: '受電設備が1箇所だけの場合は、この外箱だけを描き、エリア全体を囲う枠は描かない。',
  },
  {
    id: 'substation-area',
    abbr: 'AREA',
    nameJa: '受電設備エリアの区分枠',
    category: 'enclosure',
    tags: ['受電設備エリア', '複数箇所'],
    box: { w: 150, h: 96 },
    shapes: [rect(0, 0, 150, 96, { dash: DASH_DOT })],
    ports: [],
    status: 'open-question',
    statusNote: '「点破線」を一点鎖線として実装しています。',
    review: '受電設備が2箇所以上あるときの区分枠の線種は、この一点鎖線でよいでしょうか（見本の外箱は実線でした）。',
    note: '受電設備が2箇所以上ある場合のみ、各エリアをこの枠で囲う。1箇所の場合は描かない。',
  },
];
