import type { SymbolDef } from '../types.ts';
import { circle, dot, hline, line, path, poly, rect, text, vline } from '../shape.ts';

/** 進相設備・電源設備・外枠・結線要素 */
export const miscSymbols: SymbolDef[] = [
  {
    id: 'sc',
    abbr: 'SC',
    nameJa: '進相コンデンサ',
    category: 'compensation',
    tags: ['コンデンサ', '進相設備', '力率改善'],
    box: { w: 40, h: 40 },
    shapes: [vline(20, 0, 16), hline(16, 8, 32), hline(21, 8, 32), vline(20, 21, 40)],
    ports: [
      { id: 'in', x: 20, y: 0, dir: 'up', role: 'line' },
      { id: 'out', x: 20, y: 40, dir: 'down', role: 'line' },
    ],
    fields: [{ key: 'capacity', label: '容量', type: 'number', unit: 'kvar' }],
    note: '変圧器と並列に入るパターンがある。台数は1台〜複数台。',
  },
  {
    id: 'sr',
    abbr: 'SR',
    nameJa: '直列リアクトル',
    category: 'compensation',
    tags: ['リアクトル', '進相設備'],
    box: { w: 40, h: 44 },
    shapes: [
      vline(20, 0, 10),
      path('M 20 10 A 4 4 0 0 1 20 18 A 4 4 0 0 1 20 26 A 4 4 0 0 1 20 34'),
      vline(20, 34, 44),
    ],
    ports: [
      { id: 'in', x: 20, y: 0, dir: 'up', role: 'line' },
      { id: 'out', x: 20, y: 44, dir: 'down', role: 'line' },
    ],
    fields: [{ key: 'capacity', label: '容量', type: 'number', unit: 'kvar' }],
    note: 'コンデンサ「あり」の場合に、直列接続されるパターンとされないパターンがある。',
  },
  {
    id: 'generator',
    abbr: 'G',
    nameJa: '発電機',
    category: 'source',
    tags: ['発電機', '非常用', '常用'],
    box: { w: 40, h: 44 },
    shapes: [vline(20, 0, 10), circle(20, 24, 14), text(20, 24, 'G', { size: 13 })],
    ports: [{ id: 'out', x: 20, y: 0, dir: 'up', role: 'line' }],
    fields: [
      {
        key: 'voltageClass',
        label: '電圧区分',
        type: 'select',
        options: [
          { value: 'high', label: '高圧発電機' },
          { value: 'low', label: '低圧発電機' },
        ],
      },
      {
        key: 'usage',
        label: '用途区分',
        type: 'select',
        options: [
          { value: 'normal', label: '常用型（常に稼働）' },
          { value: 'emergency', label: '非常用型（非常時のみ稼働）' },
        ],
      },
      { key: 'capacity', label: '容量', type: 'number', unit: 'kVA' },
      { key: 'place', label: '設置場所', type: 'text', help: '非常用発電機の場合は図面に明記する' },
    ],
  },
  {
    id: 'pv',
    abbr: 'PV',
    nameJa: '太陽光発電設備',
    category: 'source',
    tags: ['太陽光', '発電所', '再エネ'],
    box: { w: 44, h: 44 },
    shapes: [
      rect(10, 14, 26, 18),
      line(10, 32, 36, 14),
      line(1, 3, 9, 10),
      poly([6, 10, 10, 11.5, 8.5, 7.5], { close: true, fill: 'solid' }),
      line(9, 0, 17, 7),
      poly([14, 7, 18, 8.5, 16.5, 4.5], { close: true, fill: 'solid' }),
      vline(23, 32, 44),
    ],
    ports: [{ id: 'out', x: 23, y: 44, dir: 'down', role: 'line' }],
    fields: [
      { key: 'capacity', label: '設備規模', type: 'number', unit: 'kW' },
      { key: 'pcsCount', label: 'PCS台数', type: 'number', unit: '台' },
    ],
    note: '太陽光発電設備の規模（大きさ）を単線結線図に情報として載せる。',
  },
  {
    id: 'battery',
    abbr: 'BATT',
    nameJa: '蓄電池（系統用蓄電所）',
    category: 'source',
    tags: ['蓄電', '系統用蓄電所'],
    box: { w: 40, h: 44 },
    shapes: [
      vline(20, 0, 12),
      hline(12, 8, 32),
      hline(16, 14, 26),
      hline(22, 8, 32),
      hline(26, 14, 26),
      vline(20, 26, 44),
    ],
    ports: [{ id: 'out', x: 20, y: 0, dir: 'up', role: 'line' }],
    fields: [
      { key: 'capacity', label: '蓄電ユニット規模', type: 'number', unit: 'kWh' },
      { key: 'gridPoleNo', label: '連携する電柱番号', type: 'text' },
      { key: 'demandSite', label: '需要場所名', type: 'text' },
    ],
    note: '構成はほぼ固定で、変更点は連携する電柱番号や需要場所名程度。',
  },
  {
    id: 'bus',
    abbr: '母線',
    nameJa: '母線',
    category: 'wiring',
    tags: ['母線', '分岐'],
    box: { w: 80, h: 12 },
    shapes: [hline(6, 0, 80, { sw: 3 })],
    ports: [
      { id: 'l', x: 0, y: 6, dir: 'left', role: 'line' },
      { id: 'r', x: 80, y: 6, dir: 'right', role: 'line' },
      { id: 'in', x: 40, y: 0, dir: 'up', role: 'line' },
    ],
    note: 'LBS/OCRから変圧器へ分岐する箇所などで使用する。',
  },
  {
    id: 'junction',
    abbr: '●',
    nameJa: '接続点（分岐点）',
    category: 'wiring',
    tags: ['分岐', '接続'],
    box: { w: 12, h: 12 },
    shapes: [dot(6, 6)],
    ports: [{ id: 'c', x: 6, y: 6, dir: 'down', role: 'line' }],
  },
  {
    id: 'substation-area',
    abbr: 'AREA',
    nameJa: '受電設備エリア（外枠）',
    category: 'enclosure',
    tags: ['キュービクル', '電気室', 'オープンフレーム式'],
    box: { w: 120, h: 80 },
    shapes: [rect(0, 0, 120, 80, { dash: '6 4' })],
    ports: [],
    fields: [
      {
        key: 'form',
        label: '形態',
        type: 'select',
        options: [
          { value: 'cubicle', label: 'キュービクル式' },
          { value: 'room-cubicle', label: '電気室（内にキュービクル）' },
          { value: 'room-open', label: 'オープンフレーム式' },
        ],
        help: '「開放型」等の表記は使わず「オープンフレーム式」に統一する。',
      },
      {
        key: 'placement',
        label: '設置場所',
        type: 'select',
        options: [
          { value: 'indoor', label: '屋内' },
          { value: 'rooftop', label: '屋上' },
          { value: 'outdoor', label: '屋外（地上）' },
          { value: 'semi-outdoor', label: '半屋外' },
        ],
        allowFreeInput: true,
      },
      { key: 'floor', label: '階層', type: 'text', help: '例: 1階 / 中2階' },
      { key: 'detail', label: '場所の補足', type: 'text', help: '例: 駐車場横' },
    ],
    defaultLabel: '電気室（1階、屋内）',
    note: '1プロジェクト内に複数の受電設備エリアが存在しうる。エリアごとに形態と設置場所のラベルを持たせる。',
  },
];
