import type { SymbolDef } from '../types.ts';
import { arrowDown, circle, earth, hline, rect, text, vline } from '../shape.ts';

/** 保護継電器・避雷器・接地 */
export const protectionSymbols: SymbolDef[] = [
  {
    id: 'ocr',
    abbr: 'OCR',
    nameJa: '過電流継電器',
    category: 'protection',
    tags: ['CB形', '保護継電器', 'CT'],
    box: { w: 40, h: 40 },
    shapes: [hline(20, 0, 9), circle(20, 20, 11), text(20, 20, 'I>', { size: 11, italic: true })],
    ports: [{ id: 'in', x: 0, y: 20, dir: 'left', role: 'secondary', label: 'CTから' }],
    fields: [
      { key: 'tapCurrent', label: '電流タップ', type: 'text', unit: 'A' },
      { key: 'tapTime', label: '時限タップ', type: 'text' },
    ],
    note: 'CB形の基本構成で、CTの次に入る。',
  },
  {
    id: 'gr',
    abbr: 'GR',
    nameJa: '地絡継電器（無方向性）',
    category: 'protection',
    tags: ['PAS', '地絡', 'ZCT'],
    box: { w: 40, h: 40 },
    shapes: [hline(20, 0, 9), circle(20, 20, 11), text(20, 20, 'GR', { size: 9 })],
    ports: [{ id: 'in', x: 0, y: 20, dir: 'left', role: 'control', label: 'ZCTから' }],
    note: 'GR方式。ZCTが入る。',
  },
  {
    id: 'dgr',
    abbr: 'DGR',
    nameJa: '地絡方向継電器（方向性）',
    category: 'protection',
    tags: ['PAS', '地絡', 'ZCT', 'ZPD'],
    box: { w: 40, h: 40 },
    shapes: [hline(20, 0, 9), circle(20, 20, 11), text(20, 20, 'DGR', { size: 8 })],
    ports: [{ id: 'in', x: 0, y: 20, dir: 'left', role: 'control', label: 'ZCT/ZPDから' }],
    note: 'DGR方式。ZCTに加えZPDが入る。GRの上位互換。',
  },
  {
    id: 'la',
    abbr: 'LA',
    nameJa: '避雷器',
    category: 'protection',
    tags: ['PAS内蔵', '雷'],
    box: { w: 40, h: 48 },
    shapes: [
      vline(20, 0, 10),
      rect(13, 10, 14, 18),
      vline(20, 12, 23),
      arrowDown(20, 26.5),
      vline(20, 28, 36),
      ...earth(20, 36),
    ],
    ports: [{ id: 'in', x: 20, y: 0, dir: 'up', role: 'line' }],
    fields: [{ key: 'ratedVoltage', label: '定格電圧', type: 'text', unit: 'V' }],
    note: 'PAS内蔵のパターンのほか、PAS内にLAが入っていない場合にPAS〜VCT間に単独で入るパターンがある（その上部にPCが入ることも）。',
  },
  {
    id: 'zpd',
    abbr: 'ZPD',
    nameJa: '零相電圧検出装置',
    nameFormal: 'ゼロポテンシャルデバイス（ユーザー呼称）',
    category: 'protection',
    tags: ['PAS', 'DGR', '零相電圧'],
    box: { w: 48, h: 48 },
    shapes: [
      vline(20, 0, 48),
      hline(20, 20, 34),
      vline(34, 20, 26),
      hline(26, 27, 41),
      hline(30, 27, 41),
      vline(34, 30, 36),
      ...earth(34, 36),
    ],
    ports: [
      { id: 'in', x: 20, y: 0, dir: 'up', role: 'line' },
      { id: 'out', x: 20, y: 48, dir: 'down', role: 'line' },
    ],
    note: 'DGR方式のときZCTに加えて入る。',
    review: 'コンデンサ分圧＋接地の形で描いている。実際の図面での描き方を確認したい。',
  },
  {
    id: 'earth',
    abbr: 'E',
    nameJa: '接地',
    category: 'protection',
    tags: ['アース', '接地'],
    box: { w: 28, h: 20 },
    shapes: [vline(14, 0, 8), ...earth(14, 8)],
    ports: [{ id: 'in', x: 14, y: 0, dir: 'up', role: 'earth' }],
    fields: [
      {
        key: 'earthType',
        label: '接地種別',
        type: 'select',
        options: [
          { value: 'A', label: 'A種' },
          { value: 'B', label: 'B種' },
          { value: 'C', label: 'C種' },
          { value: 'D', label: 'D種' },
        ],
        allowFreeInput: true,
      },
      { key: 'resistance', label: '接地抵抗値', type: 'text', unit: 'Ω' },
    ],
  },
];
