import type { FieldDef, SymbolDef } from '../types.ts';
import { blade, contact, hline, line, rect, spindle, vline } from '../shape.ts';

/** 遮断器を表す×印 */
const crossMark = (x: number, y: number, s = 3.6) => [
  line(x - s, y - s, x + s, y + s),
  line(x + s, y - s, x - s, y + s),
];

const RATED_VOLTAGE: FieldDef = {
  key: 'ratedVoltage',
  label: '定格電圧',
  type: 'select',
  options: [
    { value: '7200', label: '7200V（新）' },
    { value: '6600', label: '6600V（旧）' },
  ],
  unit: 'V',
  defaultValue: '7200',
};

const RATED_CURRENT: FieldDef = { key: 'ratedCurrent', label: '定格電流', type: 'number', unit: 'A' };

export const switchgearSymbols: SymbolDef[] = [
  {
    id: 'as',
    abbr: 'AS',
    nameJa: 'エアースイッチ',
    nameFormal: '気中開閉器（電力会社側）',
    category: 'switchgear',
    tags: ['電力会社', '引込元'],
    box: { w: 40, h: 44 },
    shapes: [vline(20, 0, 12), ...blade(20, 12, 30), vline(20, 30, 44)],
    ports: [
      { id: 'in', x: 20, y: 0, dir: 'up', role: 'line' },
      { id: 'out', x: 20, y: 44, dir: 'down', role: 'line' },
    ],
    status: 'awaiting-sample',
    statusNote: '見本待ち。',
    note: '電柱パターンのとき、引込元〜責任分界点の間に入る場合がある（電力会社側の機器）。',
  },
  {
    id: 'ds',
    abbr: 'DS',
    nameJa: '断路器（ディスコン）',
    category: 'switchgear',
    tags: ['CB形', 'ディスコン', '受電設備'],
    box: { w: 40, h: 44 },
    shapes: [vline(20, 0, 12), hline(9.5, 13, 27), ...blade(20, 12, 30), vline(20, 30, 44)],
    ports: [
      { id: 'in', x: 20, y: 0, dir: 'up', role: 'line' },
      { id: 'out', x: 20, y: 44, dir: 'down', role: 'line' },
    ],
    status: 'awaiting-sample',
    statusNote: '見本待ち。',
    note: 'CB形の基本構成で、高圧ケーブル端末の次に入る。DSの次にVTが並列接続、VCBが直列接続される。',
  },
  {
    id: 'lbs',
    abbr: 'LBS',
    nameJa: '高圧負荷開閉器',
    category: 'switchgear',
    tags: ['PFS形', '主遮断装置', '責任分界点'],
    box: { w: 48, h: 62 },
    shapes: [
      vline(24, 0, 8),
      hline(8, 15, 33),
      contact(24, 14.5, 5.5),
      line(24, 48, 13, 24),
      vline(24, 48, 62),
    ],
    ports: [
      { id: 'in', x: 24, y: 0, dir: 'up', role: 'line' },
      { id: 'out', x: 24, y: 62, dir: 'down', role: 'line' },
    ],
    fields: [RATED_VOLTAGE, RATED_CURRENT],
    status: 'open-question',
    statusNote: 'PF付LBSの見本図面から、ヒューズを外した形として描きました。',
    review: 'ヒューズなしのLBSもこの形（上部に横バー＋丸、斜めの可動刃）でよいかご確認ください。',
    note: '3点不一致のとき、この記号の中央に横線を引いて「責任分界点」と記載することがある。',
  },
  {
    id: 'lbs-pf',
    abbr: 'LBS(PF付)',
    nameJa: '限流ヒューズ付高圧負荷開閉器',
    category: 'switchgear',
    tags: ['PFS形', '主遮断装置', 'PF・S形'],
    box: { w: 48, h: 78 },
    shapes: [
      vline(24, 0, 8),
      hline(8, 15, 33),
      contact(24, 14.5, 5.5),
      line(24, 62, 12, 26),
      spindle(22.1, 56.3, 13.9, 31.7, 5),
      vline(24, 62, 78),
    ],
    ports: [
      { id: 'in', x: 24, y: 0, dir: 'up', role: 'line' },
      { id: 'out', x: 24, y: 78, dir: 'down', role: 'line' },
    ],
    fields: [
      RATED_VOLTAGE,
      RATED_CURRENT,
      { key: 'fuseCount', label: 'ヒューズ本数', type: 'number', unit: '本', defaultValue: 3, help: '図面の記載例: PF×3' },
      { key: 'fuseSpec', label: 'ヒューズ定格', type: 'text', help: '図面の記載例: 7200V G50A T40A' },
    ],
    status: 'confirmed',
    statusNote: '見本図面のとおり、上部に横バー＋丸、斜めの可動刃の上に紡錘形のヒューズを描く形にしました。',
    note: 'PFS形（PF・S形）の主遮断装置。設備容量300kVA以下で採用可能。記載例「LBS 7200V 200A PF×3 7200V G50A T40A」。',
  },
  {
    id: 'pf',
    abbr: 'PF',
    nameJa: '限流ヒューズ',
    category: 'switchgear',
    tags: ['ヒューズ', 'VT'],
    box: { w: 40, h: 44 },
    shapes: [vline(20, 0, 44), rect(15, 11, 10, 22)],
    ports: [
      { id: 'in', x: 20, y: 0, dir: 'up', role: 'line' },
      { id: 'out', x: 20, y: 44, dir: 'down', role: 'line' },
    ],
    fields: [RATED_CURRENT],
    status: 'confirmed',
    statusNote: '見本図面（VT＋PF）のとおり、導体方向に細長い長方形にしました。',
    note: 'VTの手前に入る。横向きの分岐に付く場合は90°回転して使う。',
  },
  {
    id: 'pc',
    abbr: 'PC',
    nameJa: '高圧カットアウト',
    category: 'switchgear',
    tags: ['カットアウトスイッチ', '変圧器一次側'],
    box: { w: 40, h: 44 },
    shapes: [vline(20, 0, 44), rect(13, 12, 14, 18), line(13, 30, 27, 12)],
    ports: [
      { id: 'in', x: 20, y: 0, dir: 'up', role: 'line' },
      { id: 'out', x: 20, y: 44, dir: 'down', role: 'line' },
    ],
    fields: [{ key: 'fuseRating', label: 'ヒューズ定格電流', type: 'number', unit: 'A' }],
    status: 'awaiting-sample',
    statusNote: '見本待ち。',
    note: '変圧器の手前に入るパターン、PAS〜VCT間のLAの上部に入るパターンがある。',
  },
  {
    id: 'vcb',
    abbr: 'VCB',
    nameJa: '真空遮断器',
    category: 'switchgear',
    tags: ['CB形', '主遮断装置', '責任分界点'],
    box: { w: 40, h: 44 },
    shapes: [
      vline(20, 0, 12),
      ...crossMark(20, 12),
      contact(20, 30),
      line(20, 28.2, 31, 14),
      vline(20, 30, 44),
    ],
    ports: [
      { id: 'in', x: 20, y: 0, dir: 'up', role: 'line' },
      { id: 'out', x: 20, y: 44, dir: 'down', role: 'line' },
    ],
    status: 'confirmed',
    statusNote: '×印付き開閉器（JIS式）を採用。この形でOK。',
    note: 'CB形の主遮断装置。設備容量301kVA以上では必須。すぐ下にCTが入る。',
  },
  {
    id: 'pas',
    abbr: 'PAS',
    nameJa: '区分開閉器（高圧気中開閉器）',
    category: 'switchgear',
    tags: ['区分開閉器', '電柱上', 'GR', 'DGR'],
    box: { w: 56, h: 66 },
    shapes: [
      vline(28, 0, 10),
      rect(6, 10, 44, 46),
      vline(28, 10, 30),
      line(28, 48, 17, 32),
      vline(28, 48, 66),
    ],
    ports: [
      { id: 'in', x: 28, y: 0, dir: 'up', role: 'line' },
      { id: 'out', x: 28, y: 66, dir: 'down', role: 'line' },
    ],
    slots: [
      { id: 'zct', x: 28, y: 20, label: 'ZCT（GR/DGR方式のとき内蔵）', accepts: ['zct'] },
      { id: 'vt', x: 40, y: 50, label: 'VT内蔵', accepts: ['vt'] },
      { id: 'la', x: 13, y: 48, label: 'LA内蔵', accepts: ['la'] },
      { id: 'zpd', x: 42, y: 34, label: 'ZPD（DGR方式で内蔵VTがないとき）', accepts: ['zpd'] },
    ],
    fields: [
      RATED_VOLTAGE,
      {
        key: 'ratedCurrent',
        label: '定格電流',
        type: 'select',
        options: [
          { value: '100', label: '100A' },
          { value: '200', label: '200A' },
          { value: '300', label: '300A' },
          { value: '400', label: '400A' },
        ],
        unit: 'A',
      },
      {
        key: 'control',
        label: '制御装置の種類',
        type: 'select',
        options: [
          { value: 'none', label: 'なし' },
          { value: 'gr', label: 'GR（無方向性）' },
          { value: 'dgr', label: 'DGR（方向性）' },
        ],
        defaultValue: 'dgr',
        help: 'GRはZCTが入る。DGRはZCTに加え零相電圧（内蔵VTまたはZPD）が必要。',
      },
      { key: 'builtinVt', label: 'VT内蔵', type: 'boolean', defaultValue: false },
      { key: 'builtinLa', label: 'LA内蔵', type: 'boolean', defaultValue: false },
    ],
    status: 'confirmed',
    statusNote: '見本図面のとおり実線の四角にしました。内蔵機器（ZCT/VT/LA）は個別の記号として枠内に配置します。',
    note: '記載例「PAS 7200V300A VT,LA内蔵型」。制御装置（GR/DGR）は枠の外に描き、ZCT・VTから制御線を引く。',
  },
];
